feat: add heading
vijaybalamahalingam/ZILLAZILLAKZILLA pull request #21
Opened 2023-10-19 07:48 UTC by anujapandeyy

# Description:
This pull request adds a feature: the addition of a heading to the HTML file.

### Details:

- Added an  '< h1>'  heading to the HTML file that says "zilla zilla".

- Added an  '< h2>'  heading to the file that says "KZILLA".

### BEFORE:
![image](https://github.com/vijaybalamahalingam/ZILLAZILLAKZILLA/assets/147274894/d994b01b-06cd-4f44-a510-485c7468755e)

### AFTER:
![image](https://github.com/vijaybalamahalingam/ZILLAZILLAKZILLA/assets/147274894/5bbf3c50-ca21-4739-b7ff-3409499d7014)

### Checklist
- [ ] My code follows the style guidelines of this project.
- [ ] The code follows HTML best practices and coding standards.
- [ ] I have performed a self review of my own code.

2023-10-19 16:09 UTC, Manaya20 commented
gg!!

2023-10-20 14:23 UTC, sm-sami commented
You've added a html file with no content?

2023-10-20 15:20 UTC, shawshankkumar commented
<img width="617" alt="image" src="https://github.com/vijaybalamahalingam/ZILLAZILLAKZILLA/assets/74819565/b6908ae9-9ce6-4cab-a459-04804b8e83c2">


commit names are not upto the mark

2023-10-21 14:22 UTC, sm-sami requested changes

2023-10-21 14:22 UTC, sm-sami commented on heading.html
Format this file with prettier

2023-10-21 16:35 UTC, sm-sami approved these changes
LGTM!

2023-10-21 16:35 UTC, merged