feat: Add Python Casechange Program
vijaybalamahalingam/ZILLAZILLAKZILLA pull request #30
Opened 2023-10-20 15:16 UTC by SachinPrasanth777

### Description
This PR adds ChangeCase String Python Program 
<img width="1285" alt="Screenshot 2023-10-20 at 8 17 16 PM" src="https://github.com/vijaybalamahalingam/ZILLAZILLAKZILLA/assets/142246653/cd605da7-412d-4b52-b382-8e944b286dbc">

2023-10-20 15:17 UTC, shawshankkumar commented
always try to have commit messages in lower case.

2023-10-20 15:18 UTC, shawshankkumar commented
assign these and add labels:
<img width="467" alt="image" src="https://github.com/vijaybalamahalingam/ZILLAZILLAKZILLA/assets/74819565/0f694919-6d5c-46ea-8cdf-8f680b82c5ea">

2023-10-20 15:22 UTC, SachinPrasanth777 commented
I'm not a collaborator...so will I be able to add

On Fri, 20 Oct, 2023, 20:48 Shashank Kumar, ***@***.***>
wrote:

> assign these and add labels:
> [image: image]
> <https://user-images.githubusercontent.com/74819565/276975071-0f694919-6d5c-46ea-8cdf-8f680b82c5ea.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vijaybalamahalingam/ZILLAZILLAKZILLA/pull/30#issuecomment-1772934826>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BB5IF7OKD4QAZ62N44MILQDYAKI37AVCNFSM6AAAAAA6JGE7ZSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTONZSHEZTIOBSGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-20 15:29 UTC, SachinPrasanth777 commented
I have changed the title of the pull request to lower case.

2023-10-20 16:31 UTC, SachinPrasanth777 commented
I have changed the commit message to lower case

2023-10-21 03:12 UTC, sm-sami requested changes

2023-10-21 03:12 UTC, sm-sami commented on .DS_Store
Delete this file

2023-10-21 14:05 UTC, sm-sami approved these changes
LGTM!

2023-10-21 14:05 UTC, merged